title: Tomasz Młynik  # Add a space after the period

logo: image/zdj_pr.png # Use a relative path to logo image 

description: Mathematical Physicist, PhD. My research topic is on  Positive maps, Cone structure of positive maps, Quantum information theory, Higher-order transformations and Group theory, Representation theory. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk" # Verify ownership through Search Console  

email: tomek.mlynik@gmail.com # Allow visitors to contact you
