title: <p align="center"> Tomasz Młynik </p>

logo: "/images/zdj_pr.png?raw=true"

description:
  <a href="pdf/cv.pdf">cv</a> |
  I am a PhD student at the University of Gdansk.
  My research topic is on  Positive maps, Convex structure of positive maps, Quantum information theory, Higher-order transformations and Group theory, Representation theory.

  email: tomek.mlynik [at] gmail.com
  orcid_id: https://orcid.org/0000-0003-4182-907X
  linkedin_username: https://www.linkedin.com/in/tomasz-młynik-949659163/

show_downloads: false

theme: jekyll-theme-minimal
